spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lenders
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
